namespace TheplaceEmployeeApp.Data.Enums
{
    public enum BranchName
    {
        Wuse = 1,
        Gwarinpa,
        Adeola_Odeku,
        Ahia,
        Ilupeju,
        Akowonjo,
        Ikotun,
        Aviation,
        Egbeda,
        Ilorin,
        Alapere_Warehouse,
        Oregun_warehouse,
        Ikorodu,
        Ogudu,
        HO,
        Ikeja_GRA,
        Ikeja_Ogba,
        Freedom_way,
        Jubilee_Mall,
        Lekki,
        Ikeja_Alausa,
        Surulere,
        Yaba,
        Maryland,
        Oyingbo_CK,
        Satellite,
        Circle_Mall,
        Ikota,
        Ikoyi_Plaza,
        Ikoyi_Falomo,
    }
}
